import { createRemoteJWKSet, jwtVerify } from 'npm:jose@6.2.12';
const AGENT_ID="agent:csa.master-mind",AGENT_NAME="Master Mind",PRODUCT="csa",PROJECT_REF="vphbnwzjcfxgmtyggwxl";
const GH_ISS='https://token.actions.githubusercontent.com',GH_AUD='wardale-product-lead-proof';
const GH_JWKS=createRemoteJWKSet(new URL('https://token.actions.githubusercontent.com/.well-known/jwks'),{timeoutDuration:5000});
const V_ISS='https://oidc.vercel.com/wardale-os',V_AUD='https://vercel.com/wardale-os',V_SUB='owner:wardale-os:project:wardale-app:environment:production';
const V_JWKS=createRemoteJWKSet(new URL(`${V_ISS}/.well-known/jwks`),{timeoutDuration:5000});
const REPOSITORY='Griffindor888/WARDALE-os',REPOSITORY_ID='1292250480',OWNER_ID='68334959';
const WORKFLOW='Griffindor888/WARDALE-os/.github/workflows/product-lead-proof.yml@refs/heads/main';
const BASE=Deno.env.get('SUPABASE_URL'),SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
if(BASE!==`https://${PROJECT_REF}.supabase.co`||!SERVICE)throw new Error('AGENT_RUNTIME_CONFIGURATION_REQUIRED');
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'private, no-store','x-content-type-options':'nosniff'}});
const bearer=(r:Request)=>{const h=r.headers.get('authorization')??'';return h.startsWith('Bearer ')&&h.length<=16000?h.slice(7):''};
async function github(req:Request){const t=bearer(req);if(!t)return null;try{const {payload}=await jwtVerify(t,GH_JWKS,{issuer:GH_ISS,audience:GH_AUD,algorithms:['RS256'],requiredClaims:['exp','iat','jti','repository','repository_id','repository_owner_id','ref','workflow_ref','workflow_sha','run_id','event_name'],maxTokenAge:'10m'});if(payload.repository!==REPOSITORY||payload.repository_id!==REPOSITORY_ID||payload.repository_owner_id!==OWNER_ID||payload.ref!=='refs/heads/main'||payload.workflow_ref!==WORKFLOW||!['push','workflow_dispatch'].includes(String(payload.event_name))||typeof payload.workflow_sha!=='string'||!/^[0-9a-f]{40}$/.test(payload.workflow_sha)||typeof payload.run_id!=='string'||!/^[0-9]{1,30}$/.test(payload.run_id))return null;return{revision:payload.workflow_sha,runId:payload.run_id};}catch{return null;}}
async function vercel(req:Request){const t=bearer(req);if(!t)return false;try{const {payload}=await jwtVerify(t,V_JWKS,{issuer:V_ISS,audience:V_AUD,subject:V_SUB,algorithms:['RS256'],requiredClaims:['exp','iat','sub','owner_id','project_id','environment'],maxTokenAge:'65m'});return payload.owner_id==='team_T3DA05xenMUbMVaiIwa6yj9g'&&payload.project_id==='prj_P96V6jrUqXx5ZtexX8s2ArOwcS9f'&&payload.environment==='production';}catch{return false;}}
async function count(table:string,profile?:string){const headers:Record<string,string>={apikey:SERVICE!,authorization:`Bearer ${SERVICE}`,prefer:'count=exact',range:'0-0'};if(profile)headers['accept-profile']=profile;const r=await fetch(`${BASE}/rest/v1/${table}?select=*`,{method:'HEAD',headers,redirect:'error',signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error('SOURCE_UNAVAILABLE');const m=(r.headers.get('content-range')??'').match(/\/(\d+)$/);if(!m)throw new Error('COUNT_UNAVAILABLE');return Number(m[1]);}
async function latest(){const q=new URL(`${BASE}/rest/v1/wardale_agent_operating_reports`);q.searchParams.set('agent_id',`eq.${AGENT_ID}`);q.searchParams.set('select','event_id,agent_id,agent_name,product,operation,source_revision,workflow_run_id,evidence,occurred_at');q.searchParams.set('order','occurred_at.desc');q.searchParams.set('limit','1');const r=await fetch(q,{headers:{apikey:SERVICE!,authorization:`Bearer ${SERVICE}`},redirect:'error',signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error('REPORT_READ_FAILED');const rows=await r.json();return Array.isArray(rows)&&rows.length===1?rows[0]:null;}
async function persist(auth:{revision:string,runId:string},evidence:Record<string,unknown>){const body={agent_id:AGENT_ID,agent_name:AGENT_NAME,product:PRODUCT,operation:'founder.status.report',source_repository:REPOSITORY,source_revision:auth.revision,workflow_run_id:auth.runId,evidence};const p=await fetch(`${BASE}/rest/v1/wardale_agent_operating_reports?on_conflict=agent_id,workflow_run_id`,{method:'POST',headers:{apikey:SERVICE!,authorization:`Bearer ${SERVICE}`,'content-type':'application/json',prefer:'resolution=ignore-duplicates'},body:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(5000)});if(!p.ok)throw new Error('REPORT_PERSIST_FAILED');const row=await latest();if(!row||row.workflow_run_id!==auth.runId)throw new Error('REPORT_READBACK_INVALID');return row;}
Deno.serve(async(req:Request)=>{if(req.method==='GET'){if(!req.headers.has('authorization'))return json({status:'ready',agentId:AGENT_ID,agentName:AGENT_NAME,product:PRODUCT,operation:'founder.status.report',executionAuthority:false});if(!await vercel(req))return json({error:'UNAUTHORISED'},401);try{return json({status:'connected',report:await latest()});}catch{return json({error:'REPORT_UNAVAILABLE'},503);}}
if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);const auth=await github(req);if(!auth)return json({error:'UNAUTHORISED'},401);try{const checks=await Promise.all([count("csa_commercial_enquiries",undefined),count("csa_commercial_enquiry_events",undefined),count("wardale_market_events",undefined)]);const evidence={projectRef:PROJECT_REF,checks:{"commercialEnquiries":checks[0],"commercialEnquiryEvents":checks[1],"marketEvents":checks[2]},authority:'report-only',externalActions:false};return json({status:'completed',report:await persist(auth,evidence)});}catch{return json({error:'AGENT_REPORT_UNAVAILABLE'},503);}});